version: '3.4'

services:
  nginx:
    deploy:
      labels:
        traefik.port: 8090
        traefik.frontend.rule: 'Host:${FRONTEND}'
      replicas: 4
      update_config:
        parallelism: 2
        delay: 10s
        order: start-first
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '1'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
      placement:
        constraints:
          - node.role == manager
    image: emarsys/nginx-proxy-poc:latest
    environment:
      - 'PROXY_USER=${USERNAME}'
      - 'PROXY_PASSWORD=${PASSWORD}'
      - 'PROXY_USER_NEW=${NEW_USERNAME}'
      - 'PROXY_PASSWORD_NEW=${NEW_PASSWORD}'
    networks:
      - ingress_default
networks:
  ingress_default:
    external: true
