version: "3.7"

services:
  nginx:
    image: plugins-static-ip-service
    ports:
      - "8080:8090"
    volumes:
      - "./nginx.conf:/etc/nginx/conf.d/proxy.conf:ro"
    environment:
      - "PROXY_USER=qqq"
      - "PROXY_PASSWORD=www"
      - "PROXY_USER_NEW=aaa"
      - "PROXY_PASSWORD_NEW=sss"
