version: '3.4'

services:
  nginx:
    deploy:
      labels:
        traefik.port: 8090
        traefik.frontend.rule: 'Host:${FRONTEND}'
      replicas: 2
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '1'
          memory: 1000M
        reservations:
          cpus: '0.25'
          memory: 500M
      placement:
        constraints:
          - node.role == manager
    image: emarsys/nginx-proxy-poc:8393f886547beb12573a24e9af32cb156eabf8e8
    environment:
      - 'PROXY_USER=${USERNAME}'
      - 'PROXY_PASSWORD=${PASSWORD}'
    networks:
      - ingress_default
networks:
  ingress_default:
    external: true
